Repository jplag/JPlag, pull requests merged in 2022-11, with the labels that each got.

#749 Experimental source analysis
  languages/cpp/src/main/java/de/jplag/cpp/experimental/GCCSourceAnalysis.java
  languages/cpp/src/main/java/de/jplag/cpp/experimental/SourceAnalysis.java
Labels: enhancement, major

#784 Feature: Auto Release of JAR
  .github/workflows/publish.yml
Labels: enhancement, minor

#794 Fix similarity distribution in JPlagResult
  core/src/main/java/de/jplag/JPlagResult.java
  core/src/main/java/de/jplag/reporting/reportobject/mapper/MetricMapper.java
  core/src/test/java/de/jplag/BaseCodeTest.java
  core/src/test/java/de/jplag/ParallelComparisonTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/MetricMapperTest.java
Labels: bug, minor

#801 Feature: Flattening of POM.xml
  pom.xml
Labels: bug, minor

#803 Link metamodel plagiarism paper in the EMF language Module readme files
  languages/emf-metamodel-dynamic/README.md
  languages/emf-metamodel/README.md
Labels: enhancement, minor, language

#809 Use Maven to load version of JPlag
  README.md
  cli/src/main/java/de/jplag/cli/CLI.java
  core/pom.xml
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/model/Version.java
  core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
Labels: enhancement, minor

#785 fix bug: representation for name of file and match
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/test/java/de/jplag/reporting/jsonfactory/DirectoryManagerTest.java
  core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
  core/src/test/resources/de/jplag/samples/basecode-sameNameOfSubdirectoryAndRootdirectory/A/B/A/TerrainType.java
  core/src/test/resources/de/jplag/samples/basecode-sameNameOfSubdirectoryAndRootdirectory/B/TerrainType.java
  core/src/test/resources/de/jplag/samples/basecode-sameNameOfSubdirectoryAndRootdirectory/base/TerrainType.java
  report-viewer/src/components/FilesContainer.vue
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/views/FileUploadView.vue
Labels: bug, report-viewer
