Repository jplag/JPlag, pull requests merged in 2022-09, with the labels that each got.

#636 Finalize Rust frontend test
  jplag.frontend.rust/src/test/java/de/jplag/rust/RustFrontendTest.java
Labels: enhancement, minor, language

#622 Replace ANTLR with CoreNLP in text frontend
  README.md
  jplag.frontend.text/pom.xml
  jplag.frontend.text/src/main/antlr/text.g
  jplag.frontend.text/src/main/java/de/jplag/text/AntlrParserToken.java
  jplag.frontend.text/src/main/java/de/jplag/text/InputState.java
  jplag.frontend.text/src/main/java/de/jplag/text/ParserAdapter.java
  jplag.frontend.text/src/main/java/de/jplag/text/TextToken.java
  jplag.frontend.text/src/test/java/jplag/text/TextFrontendTest.java
  pom.xml
Labels: enhancement, minor

#637 Fix assertion
  jplag.frontend.rust/src/test/java/de/jplag/rust/RustFrontendTest.java
Labels: enhancement, minor

#649 Fix language file suffix bug
  jplag.cli/src/test/java/de/jplag/cli/LanguageTest.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
Labels: bug, minor

#656 Improve logging
  jplag.frontend-utils/src/main/java/de/jplag/LanguageLoader.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
Labels: enhancement, minor

#646 Make ClusteringOptions to a record
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag.cli/src/test/java/de/jplag/cli/ClusteringTest.java
  jplag/src/main/java/de/jplag/clustering/ClusteringFactory.java
  jplag/src/main/java/de/jplag/clustering/ClusteringOptions.java
  jplag/src/main/java/de/jplag/clustering/Preprocessing.java
  jplag/src/main/java/de/jplag/clustering/algorithm/AgglomerativeClustering.java
  jplag/src/main/java/de/jplag/clustering/algorithm/SpectralClustering.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
  jplag/src/test/java/de/jplag/clustering/algorithm/ClusteringData.java
Labels: enhancement, minor

#651 Change Report Viewer Part in README.md
  README.md
Labels: enhancement, minor

#650 Migration from float to double
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag.cli/src/test/java/de/jplag/cli/ClusteringTest.java
  jplag.cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  jplag.cli/src/test/java/de/jplag/cli/SimiliarityThresholdTest.java
  jplag.endtoend-testing/src/main/java/de/jplag/endtoend/model/ExpectedResult.java
  jplag.endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
  jplag.endtoend-testing/src/test/resources/results/java/sortAlgo.json
  jplag/src/main/java/de/jplag/JPlagComparison.java
  jplag/src/main/java/de/jplag/JPlagResult.java
  jplag/src/main/java/de/jplag/clustering/Cluster.java
  jplag/src/main/java/de/jplag/clustering/ClusteringAdapter.java
  jplag/src/main/java/de/jplag/clustering/ClusteringFactory.java
  jplag/src/main/java/de/jplag/clustering/ClusteringOptions.java
  jplag/src/main/java/de/jplag/clustering/ClusteringResult.java
  jplag/src/main/java/de/jplag/clustering/algorithm/AgglomerativeClustering.java
  jplag/src/main/java/de/jplag/clustering/algorithm/InterClusterSimilarity.java
  jplag/src/main/java/de/jplag/clustering/algorithm/SpectralClustering.java
  jplag/src/main/java/de/jplag/clustering/preprocessors/PercentileThresholdProcessor.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
  jplag/src/main/java/de/jplag/options/SimilarityMetric.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/MetricMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/Cluster.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/ComparisonReport.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/TopComparison.java
  jplag/src/test/java/de/jplag/BaseCodeTest.java
  jplag/src/test/java/de/jplag/NormalComparisonTest.java
  jplag/src/test/java/de/jplag/ParallelComparisonTest.java
  jplag/src/test/java/de/jplag/TestBase.java
  jplag/src/test/java/de/jplag/clustering/ClusteringAdapterTest.java
  jplag/src/test/java/de/jplag/clustering/ClusteringResultTest.java
  jplag/src/test/java/de/jplag/clustering/algorithm/ClusteringData.java
  jplag/src/test/java/de/jplag/clustering/preprocessors/PercentilePreprocessorTest.java
  jplag/src/test/java/de/jplag/clustering/preprocessors/PreprocessingTestBase.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/ClusteringResultMapperTest.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/MetricMapperTest.java
  jplag/src/test/java/de/jplag/special/VolumeTest.java
Labels: enhancement, minor

#657 Make comparison report generation faster
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
Labels: enhancement, minor

#659 Parallel comparison file writing fix
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
Labels: bug, minor

#645 End-To-End Dokumentation and cleanup
  jplag.endtoend-testing/README.md
  jplag.endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
  jplag.endtoend-testing/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo4d1.java
  jplag.endtoend-testing/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo7.java
  jplag.endtoend-testing/src/test/resources/results/java/sortAlgo.json
Labels: enhancement, minor

#667 Consistent use of the term language module
  core/src/main/java/de/jplag/SubmissionSetBuilder.java
  core/src/test/resources/de/jplag/samples/PartialPlagiarism/A/Token.java
  language-api/src/main/java/de/jplag/LanguageLoader.java
  language-api/src/main/java/de/jplag/TokenPrinter.java
  languages/csharp/src/test/java/de/jplag/csharp/MinimalCSharpTest.java
  languages/csharp/src/test/resources/de/jplag/csharp/TestClass.cs
  languages/emf-metamodel-dynamic/README.md
  languages/emf-metamodel-dynamic/src/test/java/de/jplag/emf/dynamic/MinimalDynamicMetamodelTest.java
  languages/emf-metamodel/README.md
  languages/emf-metamodel/src/test/java/de/jplag/emf/MinimalMetamodelTest.java
  languages/golang/src/test/java/de/jplag/golang/GoLanguageTest.java
  languages/kotlin/README.md
  languages/kotlin/src/test/java/de/jplag/kotlin/KotlinLanguageTest.java
  languages/rlang/README.md
  languages/rlang/src/main/java/de/jplag/rlang/JPlagRListener.java
  languages/rlang/src/main/java/de/jplag/rlang/RParserAdapter.java
  languages/rlang/src/main/java/de/jplag/rlang/RTokenType.java
  languages/rlang/src/test/java/de/jplag/rlang/RLanguageTest.java
  languages/rust/README.md
  languages/rust/src/main/java/de/jplag/rust/Language.java
  languages/rust/src/test/java/de/jplag/rust/RustLanguageTest.java
  languages/scala/README.md
  languages/scala/src/test/java/de/jplag/scala/ScalaLanguageTest.java
  languages/text/src/test/java/jplag/text/TextLanguageTest.java
Labels: bug, minor, language

#669 Fix logging of the Java language module
  languages/java/src/main/java/de/jplag/java/JavacAdapter.java
Labels: enhancement, minor, language

#670 Update Report Viewer Readme
  README.md
  report-viewer/README.md
Labels: enhancement, minor, report-viewer

#672 fix readme to show logo again
  README.md
Labels: bug, minor

#624 Enable parallel comparison strategy by default
  README.md
  cli/src/main/java/de/jplag/CLI.java
  cli/src/main/java/de/jplag/CommandLineArgument.java
  cli/src/test/java/de/jplag/cli/ComparisonModeTest.java
  core/src/main/java/de/jplag/GreedyStringTiling.java
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/JPlagResult.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java
  core/src/main/java/de/jplag/strategy/ComparisonMode.java
  core/src/main/java/de/jplag/strategy/NormalComparisonStrategy.java
  core/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
  core/src/main/resources/de/jplag/messages.properties
  core/src/test/java/de/jplag/NormalComparisonTest.java
  core/src/test/java/de/jplag/ParallelComparisonTest.java
Labels: enhancement, major

#671 Normalized similarity range
  README.md
  cli/src/test/java/de/jplag/cli/SimiliarityThresholdTest.java
  core/src/main/java/de/jplag/JPlagComparison.java
  core/src/main/java/de/jplag/JPlagResult.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/options/SimilarityMetric.java
  core/src/main/java/de/jplag/reporting/reportobject/model/ComparisonReport.java
  core/src/main/java/de/jplag/reporting/reportobject/model/TopComparison.java
  core/src/main/resources/de/jplag/messages.properties
  core/src/test/java/de/jplag/BaseCodeTest.java
  core/src/test/java/de/jplag/NewJavaFeaturesTest.java
  core/src/test/java/de/jplag/ParallelComparisonTest.java
  core/src/test/java/de/jplag/TestBase.java
  core/src/test/java/de/jplag/special/VolumeTest.java
  endtoend-testing/src/test/resources/results/java/sortAlgo.json
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/model/Comparison.ts
  report-viewer/src/model/ComparisonListElement.ts
  report-viewer/src/model/factories/OverviewFactory.ts
  report-viewer/src/views/ComparisonView.vue
Labels: enhancement, major, java, report-viewer

#687 Fix example usage in the readme and fix submission logging
  README.md
  core/src/main/java/de/jplag/SubmissionSet.java
Labels: bug, minor

#674 Make directory arguments in JPlagOptions type-safe
  README.md
  cli/src/main/java/de/jplag/CLI.java
  cli/src/main/java/de/jplag/CommandLineArgument.java
  cli/src/test/java/de/jplag/cli/BaseCodeOptionTest.java
  core/src/main/java/de/jplag/SubmissionSetBuilder.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/test/java/de/jplag/BaseCodeTest.java
  core/src/test/java/de/jplag/LegacyBaseCodeParallelComparisonTest.java
  core/src/test/java/de/jplag/LegacyBaseCodeTest.java
  core/src/test/java/de/jplag/ParallelComparisonTest.java
  core/src/test/java/de/jplag/TestBase.java
  core/src/test/resources/de/jplag/samples/SubdirectoryBase/src/SimpleDuplicate.java
  core/src/test/resources/de/jplag/samples/SubdirectoryDuplicate/A/src/SimpleDuplicate.java
  core/src/test/resources/de/jplag/samples/SubdirectoryDuplicate/B/src/SimpleDuplicate.java
  core/src/test/resources/de/jplag/samples/SubdirectoryDuplicate/Base/src/SimpleDuplicate.java
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
Labels: enhancement, major, java

#688 Language API cleanup
  core/src/main/java/de/jplag/Submission.java
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  language-api/src/main/java/de/jplag/AbstractParser.java
  language-api/src/main/java/de/jplag/Language.java
  language-api/src/main/java/de/jplag/ParsingException.java
  language-api/src/main/java/de/jplag/Token.java
  language-api/src/main/java/de/jplag/TokenPrinter.java
  language-api/src/test/java/de/jplag/TokenPrinterTest.java
  language-testutils/src/test/java/de/jplag/testutils/TokenUtils.java
  languages/cpp/src/main/java/de/jplag/cpp/Language.java
  languages/cpp/src/main/java/de/jplag/cpp/Scanner.java
  languages/cpp/src/main/javacc/CPP.jj
  languages/csharp/src/main/java/de/jplag/csharp/CSharpParserAdapter.java
  languages/csharp/src/main/java/de/jplag/csharp/Language.java
  languages/csharp/src/test/java/de/jplag/csharp/MinimalCSharpTest.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicMetamodelToken.java
  languages/emf-metamodel-dynamic/src/test/java/de/jplag/emf/dynamic/MinimalDynamicMetamodelTest.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/Language.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/MetamodelToken.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/EcoreParser.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/EMFUtil.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/MetamodelTreeView.java
  languages/emf-metamodel/src/test/java/de/jplag/emf/MinimalMetamodelTest.java
  languages/golang/src/main/java/de/jplag/golang/GoParserAdapter.java
  languages/golang/src/main/java/de/jplag/golang/Language.java
  languages/golang/src/test/java/de/jplag/golang/GoLanguageTest.java
  languages/java/src/main/java/de/jplag/java/JavacAdapter.java
  languages/java/src/main/java/de/jplag/java/Language.java
  languages/java/src/main/java/de/jplag/java/Parser.java
  languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java
  languages/kotlin/src/main/java/de/jplag/kotlin/KotlinParserAdapter.java
  languages/kotlin/src/main/java/de/jplag/kotlin/Language.java
  languages/kotlin/src/test/java/de/jplag/kotlin/KotlinLanguageTest.java
  languages/python-3/src/main/java/de/jplag/python3/Language.java
  languages/python-3/src/main/java/de/jplag/python3/Parser.java
  languages/rlang/src/main/java/de/jplag/rlang/Language.java
  languages/rlang/src/main/java/de/jplag/rlang/RParserAdapter.java
  languages/rlang/src/test/java/de/jplag/rlang/RLanguageTest.java
  languages/rust/src/main/java/de/jplag/rust/Language.java
  languages/rust/src/main/java/de/jplag/rust/RustParserAdapter.java
  languages/rust/src/test/java/de/jplag/rust/RustLanguageTest.java
  languages/scala/src/main/scala/de/jplag/scala/Language.scala
  languages/scala/src/main/scala/de/jplag/scala/Parser.scala
  languages/scala/src/test/java/de/jplag/scala/ScalaLanguageTest.java
  languages/scheme/src/main/java/de/jplag/scheme/Language.java
  languages/scheme/src/main/java/de/jplag/scheme/Parser.java
  languages/scheme/src/main/javacc/Scheme.jj
  languages/text/src/main/java/de/jplag/text/Language.java
  languages/text/src/main/java/de/jplag/text/ParserAdapter.java
  languages/text/src/test/java/jplag/text/TextLanguageTest.java
Labels: enhancement, major

#690 Remove the legacy CLI argument verbosity
  README.md
  cli/src/main/java/de/jplag/CLI.java
  cli/src/main/java/de/jplag/CommandLineArgument.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/options/Verbosity.java
  core/src/main/java/de/jplag/strategy/SubmissionTuple.java
  core/src/main/resources/de/jplag/messages.properties
  core/src/test/java/de/jplag/TestBase.java
  language-api/src/main/java/de/jplag/LanguageLoader.java
Labels: enhancement, minor

#575 Add Swift Language Module
  README.md
  cli/pom.xml
  cli/src/test/java/de/jplag/cli/LanguageTest.java
  languages/pom.xml
  languages/swift/README.md
  languages/swift/pom.xml
  languages/swift/src/main/antlr4/de/jplag/swift/grammar/Swift5Lexer.g4
  languages/swift/src/main/antlr4/de/jplag/swift/grammar/Swift5Parser.g4
  languages/swift/src/main/java/de/jplag/swift/JPlagSwiftListener.java
  languages/swift/src/main/java/de/jplag/swift/Language.java
  languages/swift/src/main/java/de/jplag/swift/SwiftParserAdapter.java
  languages/swift/src/main/java/de/jplag/swift/SwiftTokenType.java
  languages/swift/src/main/java/de/jplag/swift/grammar/SwiftSupport.java
  languages/swift/src/test/java/de/jplag/swift/SwiftFrontendTest.java
  languages/swift/src/test/resources/de/jplag/swift/Complete.swift
Labels: enhancement, minor, language

#701 Suppress the StanfordNLP logger
  languages/text/src/main/java/de/jplag/text/ParserAdapter.java
Labels: enhancement, minor

#702 EMF modeling language fixes
  README.md
  cli/pom.xml
  cli/src/test/java/de/jplag/cli/LanguageTest.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/Language.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/Language.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/MetamodelTreeView.java
Labels: enhancement, minor

#706 Fix CLI help text header
  cli/src/main/java/de/jplag/CLI.java
Labels: bug, major

#707 Update pom.xml
  pom.xml
Labels: enhancement, minor

#714 Update README.md
  README.md
Labels: bug, minor
