Repository jplag/JPlag, pull requests merged in 2022-12, with the labels that each got.

#831 Update spotless formatter configuration file
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/CommandLineArgument.java
  cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndGeneratorTest.java
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
  formatter.xml
  languages/java/src/main/java/de/jplag/java/JavacAdapter.java
  languages/java/src/main/java/de/jplag/java/TokenGeneratingTreeScanner.java
Labels: bug, minor

#833 Relative Paths for Viewer
  report-viewer/public/index.html
  report-viewer/src/router/index.ts
  report-viewer/src/router/public-path.js
  report-viewer/vue.config.js
Labels: bug, minor

#839 Fix NPE when calling ParsingException constructors with null reason
  language-api/src/main/java/de/jplag/ParsingException.java
  language-api/src/test/java/de/jplag/ParsingExceptionTest.java
Labels: bug, minor

#816 Fix/match display off-by-one error and reenable clustering display
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  report-viewer/src/components/ClusterRadarChart.vue
  report-viewer/src/components/ClustersList.vue
  report-viewer/src/components/CodePanel.vue
  report-viewer/src/components/MatchTable.vue
  report-viewer/src/views/FileUploadView.vue
Labels: bug, minor, report-viewer

#834 Overhaul core test cases
  core/src/test/java/de/jplag/BaseCodeTest.java
  core/src/test/java/de/jplag/BasicFunctionalityTest.java
  core/src/test/java/de/jplag/InvalidSubmissionTest.java
  core/src/test/java/de/jplag/LegacyRootFolderTest.java
  core/src/test/java/de/jplag/NewJavaFeaturesTest.java
  core/src/test/java/de/jplag/OptionsTest.java
  core/src/test/java/de/jplag/ParallelComparisonTest.java
  core/src/test/java/de/jplag/RootFolderTest.java
  core/src/test/java/de/jplag/TestBase.java
  core/src/test/java/de/jplag/reporting/jsonfactory/DirectoryManagerTest.java
  core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/ClusteringResultMapperTest.java
  core/src/test/java/de/jplag/special/VolumeTest.java
  core/src/test/resources/de/jplag/samples/SimpleSingleFile/SimpleDuplicateA.java
  core/src/test/resources/de/jplag/samples/SimpleSingleFile/SimpleDuplicateB.java
Labels: enhancement, minor

#829 Fix/same submission
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  report-viewer/src/components/FilesContainer.vue
  report-viewer/src/components/MatchTable.vue
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/FileUploadView.vue
Labels: bug, minor, report-viewer
