Repository jplag/JPlag, pull requests merged in 2022-08, with the labels that each got.

#514 Cleanup some minor code issues
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  jplag.frontend-utils/src/main/java/de/jplag/AbstractParser.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Parser.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/CSharpListener.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/CSharpParserAdapter.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/grammar/CSharpPreprocessorParserBase.java
  jplag.frontend.java/src/main/java/de/jplag/java/JavaTokenConstants.java
  jplag.frontend.text/src/main/java/de/jplag/text/InputState.java
  jplag/src/main/java/de/jplag/GreedyStringTiling.java
  jplag/src/main/java/de/jplag/JPlag.java
  jplag/src/main/java/de/jplag/JPlagComparison.java
  jplag/src/main/java/de/jplag/JPlagResult.java
  jplag/src/main/java/de/jplag/Match.java
  jplag/src/main/java/de/jplag/Submission.java
  jplag/src/main/java/de/jplag/SubmissionSet.java
  jplag/src/main/java/de/jplag/SubmissionSetBuilder.java
  jplag/src/main/java/de/jplag/clustering/ClusteringFactory.java
  jplag/src/main/java/de/jplag/clustering/ClusteringResult.java
  jplag/src/main/java/de/jplag/clustering/IntegerMapping.java
  jplag/src/main/java/de/jplag/clustering/PreprocessorHelper.java
  jplag/src/main/java/de/jplag/clustering/algorithm/AgglomerativeClustering.java
  jplag/src/main/java/de/jplag/clustering/algorithm/BayesianOptimization.java
  jplag/src/main/java/de/jplag/clustering/algorithm/GaussianProcess.java
  jplag/src/main/java/de/jplag/clustering/algorithm/InterClusterSimilarity.java
  jplag/src/main/java/de/jplag/clustering/algorithm/SpectralClustering.java
  jplag/src/main/java/de/jplag/exceptions/ExitException.java
  jplag/src/main/java/de/jplag/exceptions/ReportGenerationException.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/JsonFactory.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/ComparisonReport.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/FilesOfSubmission.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/Match.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/TopComparison.java
  jplag/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java
  jplag/src/main/java/de/jplag/strategy/ComparisonMode.java
  jplag/src/main/java/de/jplag/strategy/NormalComparisonStrategy.java
  jplag/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
  jplag/src/main/java/de/jplag/strategy/SubmissionTuple.java
  jplag/src/main/resources/de/jplag/messages_de.properties
  jplag/src/main/resources/de/jplag/messages_en.properties
  jplag/src/main/resources/de/jplag/messages_es.properties
  jplag/src/main/resources/de/jplag/messages_fr.properties
  jplag/src/main/resources/de/jplag/messages_pt.properties
  jplag/src/test/java/de/jplag/clustering/algorithm/BayesianOptimizationTest.java
  jplag/src/test/java/de/jplag/clustering/algorithm/ClusteringData.java
  jplag/src/test/java/de/jplag/clustering/preprocessors/PreprocessingTestBase.java
Labels: enhancement, minor

#488 Feature: Own Logger for CLI with Error Collection
  jplag.cli/pom.xml
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/main/java/de/jplag/logger/CollectedLogger.java
  jplag.cli/src/main/java/de/jplag/logger/CollectedLoggerFactory.java
  jplag.cli/src/main/java/de/jplag/logger/Triple.java
  jplag.cli/src/main/java/org/slf4j/impl/StaticLoggerBinder.java
  jplag.frontend-testutils/src/test/java/de/jplag/testutils/TestErrorConsumer.java
  jplag.frontend-utils/src/main/java/de/jplag/AbstractParser.java
  jplag.frontend-utils/src/main/java/de/jplag/ErrorConsumer.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Language.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Parser.java
  jplag.frontend.cpp/src/main/java/de/jplag/cpp/Language.java
  jplag.frontend.cpp/src/main/java/de/jplag/cpp/Scanner.java
  jplag.frontend.cpp/src/main/javacc/CPP.jj
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/CSharpParserAdapter.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/Language.java
  jplag.frontend.csharp-6/src/test/java/de/jplag/csharp/MinimalCSharpFrontendTest.java
  jplag.frontend.java/src/main/java/de/jplag/java/JavacAdapter.java
  jplag.frontend.java/src/main/java/de/jplag/java/Language.java
  jplag.frontend.java/src/main/java/de/jplag/java/Parser.java
  jplag.frontend.kotlin/src/main/java/de/jplag/kotlin/KotlinParserAdapter.java
  jplag.frontend.kotlin/src/main/java/de/jplag/kotlin/Language.java
  jplag.frontend.kotlin/src/test/java/de/jplag/kotlin/KotlinFrontendTest.java
  jplag.frontend.python-3/src/main/java/de/jplag/python3/Language.java
  jplag.frontend.python-3/src/main/java/de/jplag/python3/Parser.java
  jplag.frontend.rlang/src/main/java/de/jplag/rlang/Language.java
  jplag.frontend.rlang/src/main/java/de/jplag/rlang/RParserAdapter.java
  jplag.frontend.rlang/src/test/java/de/jplag/rlang/RFrontendTest.java
  jplag.frontend.scheme/src/main/java/de/jplag/scheme/Language.java
  jplag.frontend.scheme/src/main/java/de/jplag/scheme/Parser.java
  jplag.frontend.scheme/src/main/javacc/Scheme.jj
  jplag.frontend.text/src/main/java/de/jplag/text/Language.java
  jplag.frontend.text/src/main/java/de/jplag/text/Parser.java
  jplag/src/main/java/de/jplag/ErrorCollector.java
  jplag/src/main/java/de/jplag/JPlag.java
  jplag/src/main/java/de/jplag/Submission.java
  jplag/src/main/java/de/jplag/SubmissionSet.java
  jplag/src/main/java/de/jplag/SubmissionSetBuilder.java
Labels: enhancement, minor, language-frontend

#552 Overhaul language interface
  jplag.frontend-utils/src/main/java/de/jplag/Language.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Language.java
  jplag.frontend.cpp/src/main/java/de/jplag/cpp/Language.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/Language.java
  jplag.frontend.java/src/main/java/de/jplag/java/Language.java
  jplag.frontend.kotlin/src/main/java/de/jplag/kotlin/Language.java
  jplag.frontend.kotlin/src/test/java/de/jplag/kotlin/KotlinFrontendTest.java
  jplag.frontend.python-3/src/main/java/de/jplag/python3/Language.java
  jplag.frontend.rlang/src/main/java/de/jplag/rlang/Language.java
  jplag.frontend.scheme/src/main/java/de/jplag/scheme/Language.java
  jplag.frontend.text/src/main/java/de/jplag/text/Language.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
Labels: enhancement, minor, language-frontend

#554 Add ignore rule for .vscode and .antlr directories
  .gitignore
Labels: enhancement, minor

#555 Overhaul text frontend to improve code quality and reduce complexity
  jplag.frontend.text/src/main/antlr/text.g
  jplag.frontend.text/src/main/java/de/jplag/text/AntlrParserToken.java
  jplag.frontend.text/src/main/java/de/jplag/text/InputState.java
  jplag.frontend.text/src/main/java/de/jplag/text/Language.java
  jplag.frontend.text/src/main/java/de/jplag/text/Parser.java
  jplag.frontend.text/src/main/java/de/jplag/text/ParserAdapter.java
  jplag.frontend.text/src/main/java/de/jplag/text/TextToken.java
  jplag.frontend.text/src/test/java/jplag/text/TextFrontendTest.java
  jplag.frontend.text/src/test/resources/FutureJavaDoc.txt
Labels: enhancement, minor, language-frontend

#566 Fix warnings of Sonarcloud
  jplag.frontend.cpp/src/main/javacc/CPP.jj
  jplag/src/main/java/de/jplag/JPlagComparison.java
  jplag/src/main/java/de/jplag/Submission.java
  jplag/src/main/java/de/jplag/SubmissionSetBuilder.java
  jplag/src/main/java/de/jplag/clustering/algorithm/BayesianOptimization.java
Labels: enhancement, minor

#551 End to End Testing (Java)
  jplag.cli/pom.xml
  jplag.endToEndTesting/README.md
  jplag.endToEndTesting/pom.xml
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/constants/TestDirectoryConstants.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/JPlagTestSuiteHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/JsonHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/JsonModel.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/ResultModel.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/TestCaseModel.java
  jplag.endToEndTesting/src/test/java/de/jplag/end_to_end_testing/JavaEndToEndTest.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1_2.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1_3.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1_4.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1_5.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo1_6.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo2.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo2_5.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo3.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo3_5.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo3_6.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo4.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo4d1.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo4d2.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo4d3.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo5.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo6.java
  jplag.endToEndTesting/src/test/resources/java/sortAlgo/SortAlgo7.java
  jplag.endToEndTesting/src/test/resources/results/JavaResult.json
  pom.xml
Labels: enhancement, minor

#570 Add Scala frontend
  README.md
  jplag.cli/pom.xml
  jplag.frontend.scala/README.md
  jplag.frontend.scala/pom.xml
  jplag.frontend.scala/src/main/scala/de/jplag/scala/Language.scala
  jplag.frontend.scala/src/main/scala/de/jplag/scala/Parser.scala
  jplag.frontend.scala/src/main/scala/de/jplag/scala/ScalaToken.scala
  jplag.frontend.scala/src/main/scala/de/jplag/scala/ScalaTokenConstants.scala
  jplag.frontend.scala/src/test/java/de/jplag/scala/ScalaFrontendTest.java
  jplag.frontend.scala/src/test/resources/de/jplag/scala/Complete.scala
  jplag.frontend.scala/src/test/resources/de/jplag/scala/Parser.scala
  jplag/pom.xml
  jplag/src/main/java/de/jplag/options/LanguageOption.java
  pom.xml
Labels: enhancement, minor, language-frontend

#573 Fix Report Viewer
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/ComparisonReportMapper.java
  report-viewer/src/components/CodePanel.vue
  report-viewer/src/components/MatchTable.vue
  report-viewer/src/views/FileUploadView.vue
Labels: bug, minor, report-viewer

#549 Frontends for EMF metamodel plagiarism detection
  README.md
  jplag.cli/pom.xml
  jplag.frontend-testutils/src/test/java/de/jplag/testutils/FileUtil.java
  jplag.frontend-testutils/src/test/java/de/jplag/testutils/TokenUtils.java
  jplag.frontend-utils/src/main/java/de/jplag/Language.java
  jplag.frontend-utils/src/main/java/de/jplag/TokenPrinter.java
  jplag.frontend.emf-metamodel-dynamic/pom.xml
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicMetamodelToken.java
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicMetamodelTokenConstants.java
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/Language.java
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/parser/DynamicEcoreParser.java
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/parser/DynamicMetamodelTokenGenerator.java
  jplag.frontend.emf-metamodel-dynamic/src/test/java/de/jplag/emf/dynamic/MinimalDynamicMetamodelTest.java
  jplag.frontend.emf-metamodel-dynamic/src/test/resources/de/jplag/models/bookStore.ecore
  jplag.frontend.emf-metamodel-dynamic/src/test/resources/de/jplag/models/bookStoreExtended.ecore
  jplag.frontend.emf-metamodel-dynamic/src/test/resources/de/jplag/models/bookStoreRenamed.ecore
  jplag.frontend.emf-metamodel/pom.xml
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/Language.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/MetamodelToken.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/MetamodelTokenConstants.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/parser/EcoreParser.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/parser/MetamodelTokenGenerator.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/util/AbstractMetamodelVisitor.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/util/EMFUtil.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/util/MetamodelTreeView.java
  jplag.frontend.emf-metamodel/src/test/java/de/jplag/emf/MinimalMetamodelTest.java
  jplag.frontend.emf-metamodel/src/test/resources/de/jplag/models/bookStore.ecore
  jplag.frontend.emf-metamodel/src/test/resources/de/jplag/models/bookStoreExtended.ecore
  jplag.frontend.emf-metamodel/src/test/resources/de/jplag/models/bookStoreRenamed.ecore
  jplag/pom.xml
  jplag/src/main/java/de/jplag/SubmissionSetBuilder.java
  jplag/src/main/java/de/jplag/options/LanguageOption.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  jplag/src/test/java/de/jplag/NormalComparisonTest.java
  pom.xml
Labels: enhancement, major, language-frontend

#587 Remove the char language module
  README.md
  jplag.cli/pom.xml
  jplag.frontend.chars/pom.xml
  jplag.frontend.chars/src/main/java/de/jplag/chars/CharToken.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Language.java
  jplag.frontend.chars/src/main/java/de/jplag/chars/Parser.java
  jplag/pom.xml
  pom.xml
Labels: enhancement, minor, language-frontend

#595 Add readme files for the EMF language modules
  jplag.frontend.emf-metamodel-dynamic/README.md
  jplag.frontend.emf-metamodel/README.md
Labels: enhancement, minor

#584 Language Overview in Readme
  README.md
Labels: enhancement, minor

#596 Replace broken LoC badge with a commit acitvity badge
  README.md
Labels: enhancement, minor

#604 Fix various sonar issues
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag.frontend-utils/src/main/java/de/jplag/TokenList.java
  jplag.frontend.cpp/src/main/javacc/CPP.jj
  jplag.frontend.csharp-6/src/main/antlr4/de/jplag/csharp/grammar/CSharpLexer.g4
  jplag.frontend.csharp-6/src/main/antlr4/de/jplag/csharp/grammar/CSharpParser.g4
  jplag.frontend.csharp-6/src/main/antlr4/de/jplag/csharp/grammar/CSharpPreprocessorParser.g4
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/grammar/CSharpLexerBase.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/grammar/CSharpParserBase.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/grammar/CSharpPreprocessorParserBase.java
  jplag.frontend.scala/pom.xml
  jplag/src/main/java/de/jplag/SubmissionSet.java
  jplag/src/main/java/de/jplag/clustering/ClusteringAdapter.java
  jplag/src/main/java/de/jplag/clustering/IntegerMapping.java
  jplag/src/main/java/de/jplag/options/LanguageOption.java
Labels: enhancement, minor

#569 Enable Multiroot for Report Viewer
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryCreator.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/ClusteringResultMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/ComparisonReportMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/MetricMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/SubmissionNameToIdMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/model/OverviewReport.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/ClusteringResultMapperTest.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/MetricMapperTest.java
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/components/IDsList.vue
  report-viewer/src/model/Overview.ts
  report-viewer/src/model/factories/OverviewFactory.ts
  report-viewer/src/store/store.ts
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/OverviewView.vue
Labels: enhancement, major, report-viewer

#607 Fix TestCase Junk files
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DummyWriter.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/FileWriter.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ToDiskWriter.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
Labels: bug, minor, report-viewer

#608 Zip ReportViewer Files
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryCreator.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
Labels: enhancement, minor, report-viewer

#589 Enforce line and column indices for all language modules
  jplag.frontend-utils/src/main/java/de/jplag/Language.java
  jplag.frontend-utils/src/main/java/de/jplag/Token.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
Labels: enhancement, minor

#610 Fix: Enable Opening of Cluster Dialogue
  report-viewer/src/components/ComparisonsTable.vue
Labels: bug, minor, report-viewer

#611 Fix CLI behavior for enabling/disabling clustering calculation
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag.cli/src/test/java/de/jplag/cli/ClusteringTest.java
  jplag.cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  jplag/src/main/java/de/jplag/clustering/Cluster.java
  jplag/src/main/java/de/jplag/clustering/ClusteringAlgorithm.java
  jplag/src/main/java/de/jplag/clustering/ClusteringFactory.java
  jplag/src/main/java/de/jplag/clustering/Preprocessing.java
Labels: bug, minor

#617 Remove unnecessary ANTLR3 dependencies
  pom.xml
Labels: enhancement, minor

#594 Add more config options to TokenPrinter
  jplag.frontend-testutils/src/test/java/de/jplag/testutils/TokenUtils.java
  jplag.frontend-utils/src/main/java/de/jplag/TokenList.java
  jplag.frontend-utils/src/main/java/de/jplag/TokenPrinter.java
  jplag.frontend-utils/src/test/java/de/jplag/TestToken.java
  jplag.frontend-utils/src/test/java/de/jplag/TokenPrinterTest.java
  jplag.frontend-utils/src/test/java/de/jplag/simple/TestTokenConstants.java
  jplag.frontend-utils/src/test/resources/de/jplag/samples/TokenPrinterTest.txt
  jplag.frontend.csharp-6/src/test/java/de/jplag/csharp/MinimalCSharpFrontendTest.java
  jplag.frontend.emf-metamodel-dynamic/src/test/java/de/jplag/emf/dynamic/MinimalDynamicMetamodelTest.java
  jplag.frontend.emf-metamodel/src/test/java/de/jplag/emf/MinimalMetamodelTest.java
  jplag.frontend.golang/src/test/java/de/jplag/golang/GoFrontendTest.java
  jplag.frontend.kotlin/src/test/java/de/jplag/kotlin/KotlinFrontendTest.java
  jplag.frontend.rlang/src/test/java/de/jplag/rlang/RFrontendTest.java
  jplag.frontend.scala/src/test/java/de/jplag/scala/ScalaFrontendTest.java
  jplag.frontend.text/src/test/java/jplag/text/TextFrontendTest.java
  jplag/src/main/java/de/jplag/Submission.java
  jplag/src/test/java/de/jplag/TestBase.java
  jplag/src/test/java/de/jplag/special/TokenPrinterTest.java
  jplag/src/test/resources/de/jplag/samples/FilesAsSubmissions/Submission1.java
  jplag/src/test/resources/de/jplag/samples/FilesAsSubmissions/Submission2.java
Labels: enhancement, minor

#585 Add Rust frontend
  README.md
  jplag.cli/pom.xml
  jplag.frontend.rust/README.md
  jplag.frontend.rust/pom.xml
  jplag.frontend.rust/src/main/antlr4/de/jplag/rust/grammar/README.md
  jplag.frontend.rust/src/main/antlr4/de/jplag/rust/grammar/RustLexer.g4
  jplag.frontend.rust/src/main/antlr4/de/jplag/rust/grammar/RustParser.g4
  jplag.frontend.rust/src/main/java/de/jplag/rust/JPlagRustListener.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/Language.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/ParserState.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/RustParserAdapter.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/RustToken.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/RustTokenConstants.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/grammar/RustLexerBase.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/grammar/RustParserBase.java
  jplag.frontend.rust/src/test/java/de/jplag/rust/RustFrontendTest.java
  jplag.frontend.rust/src/test/resources/de/jplag/rust/annotated/complete.rs.annotated
  jplag.frontend.rust/src/test/resources/de/jplag/rust/annotated/deno_core_runtime.rs.annotated
  jplag.frontend.rust/src/test/resources/de/jplag/rust/complete.rs
  jplag.frontend.rust/src/test/resources/de/jplag/rust/deno_core_runtime.rs
  jplag/src/main/java/de/jplag/options/LanguageOption.java
  pom.xml
Labels: enhancement, minor

#618 Clean-up CLI arguments and CLI help text
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag/src/main/resources/de/jplag/messages.properties
Labels: enhancement, minor

#463 Dynamic Loading of Language Frontends & Fixed behavior of JavaC
  jplag.cli/pom.xml
  jplag.cli/src/assembly/src.xml
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/main/java/de/jplag/CommandLineArgument.java
  jplag.cli/src/test/java/de/jplag/cli/LanguageOptionTest.java
  jplag.cli/src/test/java/de/jplag/cli/LanguageTest.java
  jplag.endToEndTesting/pom.xml
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/JPlagTestSuiteHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/TestCaseModel.java
  jplag.endToEndTesting/src/test/java/de/jplag/end_to_end_testing/JavaEndToEndTest.java
  jplag.frontend-utils/pom.xml
  jplag.frontend-utils/src/main/java/de/jplag/Language.java
  jplag.frontend-utils/src/main/java/de/jplag/LanguageLoader.java
  jplag.frontend.cpp/src/main/java/de/jplag/cpp/Language.java
  jplag.frontend.csharp-6/src/main/java/de/jplag/csharp/Language.java
  jplag.frontend.emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/Language.java
  jplag.frontend.emf-metamodel/src/main/java/de/jplag/emf/Language.java
  jplag.frontend.golang/src/main/java/de/jplag/golang/Language.java
  jplag.frontend.java/src/main/java/de/jplag/java/JavacAdapter.java
  jplag.frontend.java/src/main/java/de/jplag/java/Language.java
  jplag.frontend.kotlin/src/main/java/de/jplag/kotlin/Language.java
  jplag.frontend.python-3/src/main/java/de/jplag/python3/Language.java
  jplag.frontend.rlang/src/main/java/de/jplag/rlang/Language.java
  jplag.frontend.rust/src/main/java/de/jplag/rust/Language.java
  jplag.frontend.scala/src/main/resources/META-INF/services/de.jplag.Language
  jplag.frontend.scala/src/main/scala/de/jplag/scala/Language.scala
  jplag.frontend.scheme/src/main/java/de/jplag/scheme/Language.java
  jplag.frontend.text/src/main/java/de/jplag/text/Language.java
  jplag/pom.xml
  jplag/src/main/java/de/jplag/JPlag.java
  jplag/src/main/java/de/jplag/JPlagResult.java
  jplag/src/main/java/de/jplag/Submission.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
  jplag/src/main/java/de/jplag/options/LanguageOption.java
  jplag/src/test/java/de/jplag/InvalidSubmissionTest.java
  jplag/src/test/java/de/jplag/TestBase.java
  jplag/src/test/java/de/jplag/special/TokenPrinterTest.java
Labels: enhancement, major, language-frontend

#583 End To End Test Suite extended
  jplag.endToEndTesting/README.md
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/constants/TestDirectoryConstants.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/FileHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/JPlagTestSuiteHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/JsonHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/helper/TestSuiteHelper.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/ExpectedResult.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/JsonModel.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/Options.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/ResultDescription.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/ResultModel.java
  jplag.endToEndTesting/src/main/java/de/jplag/end_to_end_testing/model/TestCaseModel.java
  jplag.endToEndTesting/src/test/java/de/jplag/end_to_end_testing/EndToEndSuiteTest.java
  jplag.endToEndTesting/src/test/java/de/jplag/end_to_end_testing/JavaEndToEndTest.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1_2.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1_3.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1_4.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1_5.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo1_6.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo2.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo2_5.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo3.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo3_5.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo3_6.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo4.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo4d1.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo4d2.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo4d3.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo5.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo6.java
  jplag.endToEndTesting/src/test/resources/languageTestFiles/java/sortAlgo/SortAlgo7.java
  jplag.endToEndTesting/src/test/resources/results/JavaResult.json
  jplag.endToEndTesting/src/test/resources/results/java/sortAlgo.json
Labels: enhancement, minor

#619 Fix ComparisonView
  jplag/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  report-viewer/package-lock.json
  report-viewer/package.json
  report-viewer/src/router/index.ts
  report-viewer/src/store/store.ts
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/FileUploadView.vue
Labels: bug, minor, report-viewer

#572 Convert JPlagOption to Record (→ Read-Only)
  jplag.cli/src/main/java/de/jplag/CLI.java
  jplag.cli/src/test/java/de/jplag/cli/BaseCodeOptionTest.java
  jplag.cli/src/test/java/de/jplag/cli/ClusteringTest.java
  jplag.cli/src/test/java/de/jplag/cli/ComparisonModeTest.java
  jplag.cli/src/test/java/de/jplag/cli/LanguageTest.java
  jplag.cli/src/test/java/de/jplag/cli/MinTokenMatchTest.java
  jplag.cli/src/test/java/de/jplag/cli/OldNewRootDirectoriesArgumentTest.java
  jplag.cli/src/test/java/de/jplag/cli/SimiliarityThresholdTest.java
  jplag.cli/src/test/java/de/jplag/cli/StoredMatchesTest.java
  jplag.endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
  jplag/src/main/java/de/jplag/GreedyStringTiling.java
  jplag/src/main/java/de/jplag/JPlag.java
  jplag/src/main/java/de/jplag/JPlagResult.java
  jplag/src/main/java/de/jplag/SubmissionSet.java
  jplag/src/main/java/de/jplag/SubmissionSetBuilder.java
  jplag/src/main/java/de/jplag/options/JPlagOptions.java
  jplag/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  jplag/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/MetricMapper.java
  jplag/src/main/java/de/jplag/reporting/reportobject/mapper/SubmissionNameToIdMapper.java
  jplag/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java
  jplag/src/test/java/de/jplag/BaseCodeTest.java
  jplag/src/test/java/de/jplag/InvalidSubmissionTest.java
  jplag/src/test/java/de/jplag/NormalComparisonTest.java
  jplag/src/test/java/de/jplag/ParallelComparisonTest.java
  jplag/src/test/java/de/jplag/TestBase.java
  jplag/src/test/java/de/jplag/reporting/reportobject/mapper/MetricMapperTest.java
  jplag/src/test/java/de/jplag/special/TokenPrinterTest.java
  jplag/src/test/java/de/jplag/special/VolumeTest.java
Labels: enhancement, major, java
