Repository jplag/JPlag, pull requests merged in 2023-06, with the labels that each got.

#1100 Feature/new test structure for language modules
  docs/4.-Adding-New-Languages.md
  language-api/src/main/java/de/jplag/util/FileUtils.java
  language-testutils/src/test/java/de/jplag/testutils/LanguageModuleTest.java
  language-testutils/src/test/java/de/jplag/testutils/datacollector/FileTestData.java
  language-testutils/src/test/java/de/jplag/testutils/datacollector/InlineTestData.java
  language-testutils/src/test/java/de/jplag/testutils/datacollector/TestData.java
  language-testutils/src/test/java/de/jplag/testutils/datacollector/TestDataCollector.java
  language-testutils/src/test/java/de/jplag/testutils/datacollector/TestSourceIgnoredLinesCollector.java
  languages/kotlin/src/test/java/de/jplag/kotlin/KotlinLanguageTest.java
  languages/kotlin/src/test/resources/de/jplag/kotlin/HelloWorld.kt
Labels: enhancement, minor

#1133 Improve log readability and parse error reporting
  cli/src/main/java/de/jplag/cli/logger/CollectedLogger.java
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/Submission.java
  core/src/main/java/de/jplag/TimeUtil.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java
Labels: enhancement, minor

#1064 Implemented new cli, based on a different framework
  README.md
  cli/pom.xml
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/CliException.java
  cli/src/main/java/de/jplag/cli/CliGroupHelper.java
  cli/src/main/java/de/jplag/cli/CliOptions.java
  cli/src/main/java/de/jplag/cli/CommandLineArgument.java
  cli/src/main/java/de/jplag/cli/LanguageCandidates.java
  cli/src/main/java/de/jplag/cli/LanguageConverter.java
  cli/src/test/java/de/jplag/cli/ArgumentBuilder.java
  cli/src/test/java/de/jplag/cli/BaseCodeOptionTest.java
  cli/src/test/java/de/jplag/cli/ClusteringTest.java
  cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  cli/src/test/java/de/jplag/cli/LanguageTest.java
  cli/src/test/java/de/jplag/cli/MinTokenMatchTest.java
  cli/src/test/java/de/jplag/cli/OldNewRootDirectoriesArgumentTest.java
  cli/src/test/java/de/jplag/cli/SimilarityThresholdTest.java
  cli/src/test/java/de/jplag/cli/SimiliarityThresholdTest.java
  cli/src/test/java/de/jplag/cli/StoredMatchesTest.java
  docs/1.-How-to-Use-JPlag.md
  docs/4.-Adding-New-Languages.md
  language-api/src/main/java/de/jplag/Language.java
  language-api/src/main/java/de/jplag/options/DefaultLanguageOption.java
  language-api/src/main/java/de/jplag/options/LanguageOption.java
  language-api/src/main/java/de/jplag/options/LanguageOptions.java
  language-api/src/main/java/de/jplag/options/OptionType.java
Labels: enhancement, major

#1143 Fix bug in the Java language tests
  languages/java/src/test/java/de/jplag/java/JavaIfElseTest.java
Labels: bug, minor

#1144 Improve test result visualization for the view file tests
  languages/emf-metamodel/src/test/java/de/jplag/emf/AbstractEmfTest.java
Labels: enhancement, minor

#1146 Report Viewer SonarLint
  .github/workflows/sonarcloud-report-viewer.yml
  report-viewer/sonar-project.properties
Labels: enhancement, minor, report-viewer

#1156 Adjust JPlag descriptions
  cli/src/main/java/de/jplag/cli/CLI.java
Labels: enhancement, minor
