Repository jplag/JPlag, pull requests merged in 2023-12, with the labels that each got.

#1361 Readme in result zip file
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/jsonfactory/DummyWriter.java
  core/src/main/java/de/jplag/reporting/jsonfactory/FileWriter.java
  core/src/main/java/de/jplag/reporting/jsonfactory/ToDiskWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/DummyWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/FileWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/JsonWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/TextWriter.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
Labels: enhancement, minor

#1413 Sorting and filtering on cluster table
  report-viewer/src/components/ComparisonTableFilter.vue
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/components/SearchBarComponent.vue
  report-viewer/src/views/ClusterView.vue
  report-viewer/src/views/OverviewView.vue
Labels: enhancement, minor, report-viewer

#1434 cli default values
  cli/src/main/java/de/jplag/cli/CliOptions.java
  languages/java/src/main/java/de/jplag/java/JavaLanguage.java
Labels: bug, enhancement, minor
