Repository jplag/JPlag, pull requests merged in 2023-05, with the labels that each got.

#1038 Fix comparison view not working in local mode
  core/src/main/java/de/jplag/reporting/FilePathUtil.java
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/model/SubmissionFileIndex.java
  docs/6.-Report-File-Generation.md
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/FileUploadView.vue
  report-viewer/src/views/OverviewView.vue
Labels: bug, minor, report-viewer

#1041 Add static JPlag::run
  README.md
  cli/src/main/java/de/jplag/cli/CLI.java
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/SubmissionSetBuilder.java
  core/src/test/java/de/jplag/NormalizationTest.java
  core/src/test/java/de/jplag/TestBase.java
  core/src/test/java/de/jplag/special/ReadmeCodeExampleTest.java
  docs/1.-How-to-Use-JPlag.md
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndGeneratorTest.java
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
Labels: enhancement, minor

#1067 Print the number of tokens when it’s too little
  core/src/main/java/de/jplag/SubmissionSet.java
Labels: enhancement, minor

#1036 File total tokens added to report output
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/model/Match.java
Labels: enhancement, minor

#1081 Fix supported C# version in README
  README.md
  docs/2.-Supported-Languages.md
Labels: enhancement, minor

#1080 Extract APPLY token for function calls with literal arguments
  languages/cpp2/src/main/java/de/jplag/cpp2/CPPTokenListener.java
  languages/cpp2/src/test/java/de/jplag/cpp2/TokenExtractionTest.java
Labels: bug, minor

#1070 Changed the ClusteringFactory to only do something, if there are any …
  core/src/main/java/de/jplag/clustering/ClusteringFactory.java
Labels: bug, minor

#1088 Merge main into develop
  README.md
  pom.xml
Labels: release

#1089 Increase development version to 4.4.0-SNAPSHOT.
  pom.xml
Labels: release

#856 Prototype for EMF model instance language module
  .gitattributes
  .gitignore
  README.md
  cli/pom.xml
  cli/src/test/java/de/jplag/cli/LanguageTest.java
  core/src/main/java/de/jplag/SubmissionSetBuilder.java
  coverage-report/pom.xml
  language-api/src/main/java/de/jplag/Language.java
  language-api/src/main/java/de/jplag/Token.java
  language-api/src/main/java/de/jplag/TokenTrace.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicMetamodelToken.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicMetamodelTokenType.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/Language.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/parser/DynamicEcoreParser.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/parser/DynamicElementTokenizer.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/parser/DynamicMetamodelTokenGenerator.java
  languages/emf-metamodel-dynamic/src/test/java/de/jplag/emf/dynamic/MinimalDynamicMetamodelTest.java
  languages/emf-metamodel/pom.xml
  languages/emf-metamodel/src/main/java/de/jplag/emf/MetamodelToken.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/MetamodelTokenType.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/normalization/ContainmentOrderNormalizer.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/normalization/ModelSorter.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/normalization/TokenVectorGenerator.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/EcoreParser.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/MetamodelElementTokenizer.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/MetamodelTokenGenerator.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/ModelingElementTokenizer.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/AbstractMetamodelVisitor.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/AbstractModelView.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/EmfaticModelView.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/util/MetamodelTreeView.java
  languages/emf-metamodel/src/test/java/de/jplag/emf/AbstractEmfTest.java
  languages/emf-metamodel/src/test/java/de/jplag/emf/MinimalMetamodelTest.java
  languages/emf-metamodel/src/test/java/de/jplag/emf/util/EmfaticModelViewTest.java
  languages/emf-metamodel/src/test/java/de/jplag/emf/util/MetamodelTreeViewTest.java
  languages/emf-metamodel/src/test/resources/de/jplag/treeview/bookStore.ecore.treeview
  languages/emf-metamodel/src/test/resources/de/jplag/treeview/bookStoreExtended.ecore.treeview
  languages/emf-metamodel/src/test/resources/de/jplag/treeview/bookStoreExtendedRefactor.ecore.treeview
  languages/emf-metamodel/src/test/resources/de/jplag/treeview/bookStoreRenamed.ecore.treeview
  languages/emf-model/pom.xml
  languages/emf-model/src/main/java/de/jplag/emf/model/Language.java
  languages/emf-model/src/main/java/de/jplag/emf/model/parser/DynamicModelParser.java
  languages/emf-model/src/test/java/de/jplag/emf/model/BookStoreFactory.java
  languages/emf-model/src/test/java/de/jplag/emf/model/MinimalModelInstanceTest.java
  languages/emf-model/src/test/resources/de/jplag/books/bookStore.ecore
  languages/emf-model/src/test/resources/de/jplag/books/bookStore.xml
  languages/emf-model/src/test/resources/de/jplag/books/bookStore2.xml
  languages/pom.xml
  pom.xml
Labels: enhancement, major, language

#1069 Feature/adopt python grammar fixes
  languages/python-3/src/main/antlr4/de/jplag/python3/grammar/Python3.g4
  languages/python-3/src/main/antlr4/de/jplag/python3/grammar/Python3Lexer.g4
  languages/python-3/src/main/antlr4/de/jplag/python3/grammar/Python3Parser.g4
  languages/python-3/src/main/java/de/jplag/python3/JplagPython3Listener.java
  languages/python-3/src/main/java/de/jplag/python3/grammar/Python3LexerBase.java
  languages/python-3/src/main/java/de/jplag/python3/grammar/Python3ParserBase.java
  languages/python-3/src/test/java/de/jplag/python3/PythonLanguageCoverageTest.java
  languages/python-3/src/test/java/de/jplag/python3/PythonLanguageSequenceTest.java
  languages/python-3/src/test/resources/de/jplag/python3/base_features.py
  languages/python-3/src/test/resources/de/jplag/python3/log.py
  languages/python-3/src/test/resources/de/jplag/python3/streams.py
  languages/python-3/src/test/resources/de/jplag/python3/test_utils.py
  languages/python-3/src/test/resources/de/jplag/python3/unicode.py
Labels: bug, enhancement, minor, language
