Repository jplag/JPlag, pull requests merged in 2024-06, with the labels that each got.

#1796 Refactor Json Match
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/model/CodePosition.java
  core/src/main/java/de/jplag/reporting/reportobject/model/Match.java
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/version.json
  report-viewer/tests/e2e/Cluster.spec.ts
  report-viewer/tests/e2e/assets/result_small_cluster.zip
  report-viewer/tests/unit/model/factories/ValidComparison.json
  report-viewer/tests/unit/model/factories/ValidOverview.json
Labels: enhancement, minor, report-viewer

#1744 Added new framework for Cli-Tests
  cli/src/test/java/de/jplag/cli/AdvancedGroupTest.java
  cli/src/test/java/de/jplag/cli/BaseCodeOptionTest.java
  cli/src/test/java/de/jplag/cli/CheckResultFileWritableTest.java
  cli/src/test/java/de/jplag/cli/ClusteringTest.java
  cli/src/test/java/de/jplag/cli/CommandLineInterfaceTest.java
  cli/src/test/java/de/jplag/cli/LanguageTest.java
  cli/src/test/java/de/jplag/cli/MergingOptionsTest.java
  cli/src/test/java/de/jplag/cli/MinTokenMatchTest.java
  cli/src/test/java/de/jplag/cli/OldNewRootDirectoriesArgumentTest.java
  cli/src/test/java/de/jplag/cli/SimilarityThresholdTest.java
  cli/src/test/java/de/jplag/cli/StoredMatchesTest.java
  cli/src/test/java/de/jplag/cli/test/CliArgument.java
  cli/src/test/java/de/jplag/cli/test/CliArgumentBuilder.java
  cli/src/test/java/de/jplag/cli/test/CliResult.java
  cli/src/test/java/de/jplag/cli/test/CliTest.java
Labels: enhancement, major

#1823 Changed the final frame of the idle bar to be easier to identify.
  cli/src/main/java/de/jplag/cli/logger/IdleBar.java
Labels: enhancement, minor

#1826 Clean up logger
  cli/src/main/java/de/jplag/cli/logger/CliProgressBarProvider.java
  cli/src/main/java/de/jplag/cli/logger/CollectedLogger.java
  cli/src/main/java/de/jplag/cli/logger/JPlagLoggerBase.java
Labels: enhancement, minor

#1827 Fix a bug where the basecode submission was not normalized
  core/src/main/java/de/jplag/SubmissionSet.java
Labels: bug, minor

#1751 Added command line option for log-level
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/logger/CliProgressBarProvider.java
  cli/src/main/java/de/jplag/cli/logger/CollectedLogger.java
  cli/src/main/java/de/jplag/cli/logger/VoidProgressBar.java
  cli/src/main/java/de/jplag/cli/options/CliOptions.java
  cli/src/test/java/de/jplag/cli/logger/VoidProgressBarTest.java
  report-viewer/package-lock.json
Labels: enhancement, minor

#1803 Enhance Distribution Diagramm
  report-viewer/src/components/DistributionDiagram.vue
  report-viewer/src/components/distributionDiagram/DistributionDiagram.vue
  report-viewer/src/components/distributionDiagram/DistributionDiagramOptions.vue
  report-viewer/src/model/Distribution.ts
  report-viewer/src/model/ui/DistributionChartConfig.ts
  report-viewer/src/stores/store.ts
  report-viewer/src/views/OverviewView.vue
  report-viewer/tests/e2e/Distribution.spec.ts
  report-viewer/tests/unit/model/Distribution.test.ts
Labels: enhancement, report-viewer
