Repository jplag/JPlag, pull requests merged in 2024-02, with the labels that each got.

#1512 Fix code highlighting
  docs/4.-Adding-New-Languages.md
  report-viewer/src/components/fileDisplaying/CodePanel.vue
  report-viewer/src/components/fileDisplaying/FilesContainer.vue
  report-viewer/src/model/Language.ts
  report-viewer/src/utils/CodeHighlighter.ts
  report-viewer/src/viewWrapper/ComparisonViewWrapper.vue
  report-viewer/src/views/ComparisonView.vue
Labels: report-viewer

#1525 Update develop from main
  report-viewer/package-lock.json
Labels: release

#1416 ImmediatlyWriteZip
  cli/src/main/java/de/jplag/cli/CLI.java
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/DummyResultWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/DummyWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/FileWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/JPlagResultWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/JsonWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/TextWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/writer/ZipWriter.java
  core/src/test/java/de/jplag/reporting/reportobject/ReportObjectFactoryTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
  core/src/test/java/de/jplag/special/ReadmeCodeExampleTest.java
  docs/1.-How-to-Use-JPlag.md
Labels: enhancement, minor

#1527 Fix Java version badge in readme
  README.md
Labels: bug, minor

#1526 Increase development version to 5.0.0-SNAPSHOT.
  pom.xml
Labels: release

#1530 Renamed the submissions for the demo.
  .github/workflows/files/progpedia.zip
Labels: enhancement, minor

#1548 bump husky to v9
  report-viewer/.husky/pre-commit
  report-viewer/package-lock.json
  report-viewer/package.json
Labels: dependencies, report-viewer

#1549 Remove isDemo print
  report-viewer/src/components/VersionInfoComponent.vue
Labels: report-viewer

#1551 Fix submission file copying
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
Labels: bug, minor, report-viewer

#1550 Changes to MatchMerging as its tests by nils.
  core/src/main/java/de/jplag/merging/MatchMerging.java
  core/src/test/java/de/jplag/merging/MergingTest.java
  core/src/test/resources/de/jplag/samples/merging/sanityA.java
  core/src/test/resources/de/jplag/samples/merging/sanityB.java
Labels: bug, enhancement, minor

#1553 Fixed bug in the end-to-end test, that occurred on mac, due to symbolic links.
  endtoend-testing/src/main/java/de/jplag/endtoend/helper/FileHelper.java
Labels: bug, minor

#1516 File-based Similarity in the Comparison View
  core/src/main/java/de/jplag/Submission.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/model/SubmissionFile.java
  core/src/main/java/de/jplag/reporting/reportobject/model/SubmissionFileIndex.java
  report-viewer/src/components/fileDisplaying/CodePanel.vue
  report-viewer/src/components/fileDisplaying/FilesContainer.vue
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/stores/state.ts
  report-viewer/src/stores/store.ts
  report-viewer/src/utils/fileHandling/ZipFileHandler.ts
  report-viewer/tests/unit/model/factories/ComparisonFactory.test.ts
Labels: enhancement, minor, report-viewer

#1515 Link to repo in Report Viewer
  report-viewer/package-lock.json
  report-viewer/package.json
  report-viewer/src/components/RepositoryReference.vue
  report-viewer/src/components/VersionInfoComponent.vue
  report-viewer/src/viewWrapper/ClusterViewWrapper.vue
  report-viewer/src/viewWrapper/ComparisonViewWrapper.vue
  report-viewer/src/viewWrapper/InformationViewWrapper.vue
  report-viewer/src/viewWrapper/OverviewViewWrapper.vue
  report-viewer/src/views/ClusterView.vue
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/FileUploadView.vue
  report-viewer/src/views/InformationView.vue
  report-viewer/src/views/OverviewView.vue
Labels: enhancement, minor, report-viewer

#1554 Default to System Dark mode
  report-viewer/src/stores/store.ts
Labels: report-viewer

#1552 Fix line breaks in comparison view
  report-viewer/src/components/fileDisplaying/CodePanel.vue
Labels: bug, report-viewer

#1533 Show similarity for each submission
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/model/ComparisonReport.java
  report-viewer/src/components/TextInformation.vue
  report-viewer/src/components/ToolTipComponent.vue
  report-viewer/src/model/Comparison.ts
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/model/ui/ToolTip.ts
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/OverviewView.vue
Labels: enhancement, minor, report-viewer

#1556 Move files in report viewer
  report-viewer/src/components/fileDisplaying/CodePanel.vue
  report-viewer/src/components/fileDisplaying/FilesContainer.vue
  report-viewer/src/model/Comparison.ts
  report-viewer/src/model/File.ts
  report-viewer/src/model/factories/BaseFactory.ts
  report-viewer/src/model/fileHandling/FileHandler.ts
  report-viewer/src/model/fileHandling/JsonFileHandler.ts
  report-viewer/src/model/fileHandling/ZipFileHandler.ts
  report-viewer/src/model/ui/DistributionChartConfig.ts
  report-viewer/src/stores/state.ts
  report-viewer/src/stores/store.ts
  report-viewer/src/views/FileUploadView.vue
Labels: report-viewer

#1563 Match merging: Use default values for CLI
  cli/src/main/java/de/jplag/cli/CliOptions.java
  cli/src/test/java/de/jplag/cli/MergingOptionsTest.java
  core/src/main/java/de/jplag/merging/MergingOptions.java
Labels: bug, minor

#1479 Feature/normalization option
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/CliOptions.java
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/Submission.java
  core/src/main/java/de/jplag/SubmissionSet.java
  core/src/main/java/de/jplag/exceptions/ConfigurationException.java
  core/src/main/java/de/jplag/options/JPlagOptions.java
  language-antlr-utils/src/main/java/de/jplag/antlr/AbstractAntlrLanguage.java
  language-antlr-utils/src/test/java/de/jplag/antlr/LanguageTest.java
  language-api/src/main/java/de/jplag/Language.java
  languages/c/src/main/java/de/jplag/c/CLanguage.java
  languages/cpp/src/main/java/de/jplag/cpp/CPPLanguage.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/EmfLanguage.java
  languages/golang/src/main/java/de/jplag/golang/GoLanguage.java
  languages/java/src/main/java/de/jplag/java/JavaLanguage.java
  languages/python-3/src/main/java/de/jplag/python3/PythonLanguage.java
  languages/rlang/src/main/java/de/jplag/rlang/RLanguage.java
  languages/rust/src/main/java/de/jplag/rust/RustLanguage.java
  languages/scala/src/main/scala/de/jplag/scala/ScalaLanguage.scala
  languages/scala/src/test/java/de/jplag/scala/ScalaLanguageTest.java
  languages/scheme/src/main/java/de/jplag/scheme/SchemeLanguage.java
  languages/scxml/src/main/java/de/jplag/scxml/ScxmlLanguage.java
  languages/swift/src/main/java/de/jplag/swift/SwiftLanguage.java
  languages/text/src/main/java/de/jplag/text/NaturalLanguage.java
  languages/typescript/src/main/java/de/jplag/typescript/TypeScriptLanguage.java
Labels: enhancement, minor

#1567 Fix: Old cpp language names not found
  report-viewer/src/model/Language.ts
  report-viewer/src/utils/CodeHighlighter.ts
Labels: bug, report-viewer

#1555 remove duplicate info about token count
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/model/Match.java
Labels: enhancement, minor

#1570 Fix bugs in CLI error handling
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/LanguageLoader.java
Labels: bug, minor

#1568 Fixed a bug in the creation of the result due to missing slashes.
  core/src/main/java/de/jplag/reporting/FilePathUtil.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/test/java/de/jplag/reporting/FilePathUtilTest.java
Labels: bug, minor

#1433 Implemented progress bars for the cli
  cli/pom.xml
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/logger/TongfeiProgressBar.java
  cli/src/main/java/de/jplag/cli/logger/TongfeiProgressBarProvider.java
  core/src/main/java/de/jplag/SubmissionFileData.java
  core/src/main/java/de/jplag/SubmissionSet.java
  core/src/main/java/de/jplag/SubmissionSetBuilder.java
  core/src/main/java/de/jplag/logging/ProgressBar.java
  core/src/main/java/de/jplag/logging/ProgressBarLogger.java
  core/src/main/java/de/jplag/logging/ProgressBarProvider.java
  core/src/main/java/de/jplag/logging/ProgressBarType.java
  core/src/main/java/de/jplag/strategy/AbstractComparisonStrategy.java
  core/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
  core/src/test/java/de/jplag/NormalizationTest.java
Labels: enhancement, major

#1571 Remove some unused code
  core/src/main/java/de/jplag/NumberOfArgumentValues.java
  core/src/main/java/de/jplag/SubsequenceHashLookupTable.java
  core/src/main/java/de/jplag/exceptions/ConfigurationException.java
  language-antlr-utils/pom.xml
Labels: enhancement, minor

#1176 Internal Report Viewer: host and use the the report viewer locally
  .github/workflows/maven.yml
  .github/workflows/publish.yml
  .github/workflows/sonarcloud-branch.yml
  .github/workflows/sonarcloud-pr.yml
  .github/workflows/spotless.yml
  README.md
  cli/pom.xml
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/CliOptions.java
  cli/src/main/java/de/jplag/cli/JPlagMode.java
  cli/src/main/java/de/jplag/cli/server/ContentType.java
  cli/src/main/java/de/jplag/cli/server/HttpRequestMethod.java
  cli/src/main/java/de/jplag/cli/server/ReportViewer.java
  cli/src/main/java/de/jplag/cli/server/ResponseData.java
  cli/src/main/java/de/jplag/cli/server/Routing.java
  cli/src/main/java/de/jplag/cli/server/RoutingAlias.java
  cli/src/main/java/de/jplag/cli/server/RoutingFallback.java
  cli/src/main/java/de/jplag/cli/server/RoutingPath.java
  cli/src/main/java/de/jplag/cli/server/RoutingResources.java
  cli/src/main/java/de/jplag/cli/server/RoutingStaticFile.java
  cli/src/main/java/de/jplag/cli/server/RoutingTree.java
  cli/src/main/resources/README.md
  cli/src/test/java/de/jplag/cli/ReportViewerTest.java
  cli/src/test/java/de/jplag/cli/server/RoutingFallbackTest.java
  cli/src/test/java/de/jplag/cli/server/RoutingPathTest.java
  cli/src/test/java/de/jplag/cli/server/RoutingResourcesTest.java
  cli/src/test/java/de/jplag/cli/server/RoutingStaticFileTest.java
  cli/src/test/java/de/jplag/cli/server/RoutingTreeTest.java
  cli/src/test/resources/testResource.txt
  endtoend-testing/src/main/java/de/jplag/endtoend/model/ResultDescription.java
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/components/NameElement.vue
  report-viewer/src/model/factories/BaseFactory.ts
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/router/index.ts
  report-viewer/src/stores/store.ts
  report-viewer/src/viewWrapper/ComparisonViewWrapper.vue
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/FileUploadView.vue
  report-viewer/tests/unit/model/factories/ComparisonFactory.test.ts
Labels: enhancement, major, report-viewer

#1575 Changed progress bar style to ascii
  cli/src/main/java/de/jplag/cli/logger/TongfeiProgressBarProvider.java
Labels: enhancement, minor

#1573 Removed unused DirectoryManager
  cli/src/main/java/de/jplag/cli/CLI.java
  core/src/main/java/de/jplag/reporting/jsonfactory/DirectoryManager.java
  core/src/test/java/de/jplag/reporting/jsonfactory/DirectoryManagerTest.java
Labels: bug, minor

#1578 Set minimum report viewer version to 4.2.0
  report-viewer/src/model/factories/OverviewFactory.ts
  report-viewer/src/router/index.ts
  report-viewer/src/version.json
  report-viewer/tests/unit/model/factories/ValidNewOverview.json
Labels: bug, minor, report-viewer

#1577 Change JPlag revision to v5.0.0
  pom.xml
Labels: release

#1579 Fix missing line break in CLI help text with workaround
  cli/src/main/java/de/jplag/cli/CliOptions.java
Labels: bug, minor

#1580 Update main readme for the upcoming 5.0.0 release
  README.md
Labels: enhancement, minor, release

#1582 Update 1.-How-to-Use-JPlag.md
  docs/1.-How-to-Use-JPlag.md
Labels: enhancement, minor, release

#1583 Update Home.md in the Wiki
  docs/Home.md
Labels: enhancement, minor, release

#1591 Fix slash issues
  core/src/main/java/de/jplag/reporting/FilePathUtil.java
Labels: bug, minor

#1594 Update develop from main
  core/src/main/java/de/jplag/reporting/FilePathUtil.java
  pom.xml
Labels: release

#1596 Change development revision to 5.1.0-SNAPSHOT
  pom.xml
Labels: release

#1595 fix broken edge click on cluster chart
  report-viewer/src/components/ClusterGraph.vue
Labels: bug, report-viewer

#1608 Adapt deploy action to also trigger when release drafts are published
  .github/workflows/publish.yml
Labels: bug, minor, github_actions

#1615 Fix sonar link of the coverage badge
  README.md
Labels: bug, minor

#1614 Avoided null pointer exception in JPlagGoListener.
  languages/golang/src/main/java/de/jplag/golang/JPlagGoListener.java
Labels: bug, minor, language
