Repository jplag/JPlag, pull requests merged in 2025-07, with the labels that each got.

#2466 Enable searching by anonymized name
  report-viewer/src/components/ComparisonsTable.vue
Labels: enhancement, minor, report-viewer

#2463 Adjust dev-demo path
  report-viewer/vite.config.ts
Labels: enhancement, report-viewer

#2478 Fix merging matches across files
  core/src/main/java/de/jplag/merging/MatchMerging.java
  core/src/test/java/de/jplag/TestBase.java
  core/src/test/java/de/jplag/merging/MatchMergingTest.java
  core/src/test/resources/de/jplag/samples/crossFile/first/Hotel.java
  core/src/test/resources/de/jplag/samples/crossFile/first/Room.java
  core/src/test/resources/de/jplag/samples/crossFile/second/Hotel.java
  core/src/test/resources/de/jplag/samples/crossFile/second/Room.java
Labels: bug, minor

#2488 Add JPlag Website Stub
  website/.gitignore
  website/.vitepress/config.mts
  website/.vitepress/theme/index.js
  website/PaperHighlight.vue
  website/TalkHighlight.vue
  website/download/index.md
  website/index.css
  website/index.md
  website/package-lock.json
  website/package.json
  website/public/favicon.ico
  website/public/img/code-dark.svg
  website/public/img/code-light.svg
  website/public/img/jplag-logo-dark.png
  website/public/img/jplag-logo-light.png
  website/public/img/opensource-dark.svg
  website/public/img/opensource-light.svg
  website/public/img/paper-dark.svg
  website/public/img/paper-light.svg
  website/public/img/performance-dark.svg
  website/public/img/performance-light.svg
  website/public/img/resilient-dark.svg
  website/public/img/resilient-light.svg
  website/public/img/screenshot1.png
  website/public/img/screenshot2.png
  website/public/img/screenshot3.png
  website/public/img/talk-dark.svg
  website/public/img/talk-light.svg
  website/publications/bib.js
  website/publications/index.md
Labels: enhancement, major, wiki

#2470 Check that content of record and interface match
  .github/workflows/match-record-to-interface.yml
  .github/workflows/scripts/matchRecordToInterface.py
  report-viewer/src/model/CliOptions.ts
  report-viewer/src/model/Match.ts
  report-viewer/src/model/factories/ComparisonFactory.ts
  report-viewer/src/model/factories/SubmissionMappingsFactory.ts
Labels: enhancement, minor

#2511 Dissolve the shared parser superclass
  language-antlr-utils/src/main/java/de/jplag/antlr/AbstractAntlrParserAdapter.java
  language-api/src/main/java/de/jplag/AbstractParser.java
  languages/c/src/main/java/de/jplag/c/Scanner.java
  languages/c/src/main/javacc/CPP.jj
  languages/cpp/src/main/java/de/jplag/cpp/CPPParserAdapter.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/parser/EcoreParser.java
  languages/emf-model/src/main/java/de/jplag/emf/model/parser/DynamicModelParser.java
  languages/java/src/main/java/de/jplag/java/JavacAdapter.java
  languages/java/src/main/java/de/jplag/java/Parser.java
  languages/llvmir/src/main/java/de/jplag/llvmir/LLVMIRParserAdapter.java
  languages/rust/src/main/java/de/jplag/rust/RustParserAdapter.java
  languages/scala/src/main/scala/de/jplag/scala/Parser.scala
  languages/scheme/src/main/java/de/jplag/scheme/Parser.java
  languages/scxml/src/main/java/de/jplag/scxml/parser/ScxmlParserAdapter.java
  languages/text/src/main/java/de/jplag/text/ParserAdapter.java
Labels: enhancement, minor, language

#2517 Frequency determination (fix incorrect merge)
  core/src/main/java/de/jplag/highlightextraction/CompleteMatchesStrategy.java
  core/src/main/java/de/jplag/highlightextraction/ContainedMatchesStrategy.java
  core/src/main/java/de/jplag/highlightextraction/FrequencyDetermination.java
  core/src/main/java/de/jplag/highlightextraction/FrequencyStrategies.java
  core/src/main/java/de/jplag/highlightextraction/FrequencyStrategy.java
  core/src/main/java/de/jplag/highlightextraction/SubMatchesStrategy.java
  core/src/main/java/de/jplag/highlightextraction/SubSequenceUtil.java
  core/src/main/java/de/jplag/highlightextraction/WindowOfMatchesStrategy.java
  core/src/test/java/de/jplag/highlightextraction/frequencydetermination/StrategyIntegrationTest.java
  core/src/test/java/de/jplag/highlightextraction/frequencydetermination/StrategyTest.java
Labels: enhancement, major

#2514 Rewrite of the scala module in java
  languages/scala/pom.xml
  languages/scala/src/main/scala/de/jplag/scala/Parser.scala
  languages/scala/src/main/scala/de/jplag/scala/ScalaLanguage.java
  languages/scala/src/main/scala/de/jplag/scala/ScalaLanguage.scala
  languages/scala/src/main/scala/de/jplag/scala/ScalaParser.java
  languages/scala/src/main/scala/de/jplag/scala/TraverserRecord.java
  languages/scala/src/test/java/de/jplag/scala/ScalaLanguageTest.java
  languages/scala/src/test/resources/de/jplag/scala/Parser.scala
Labels: enhancement, minor, language

#2534 Update develop from main
  cli/pom.xml
  core/pom.xml
  language-antlr-utils/pom.xml
  language-api/pom.xml
  language-testutils/pom.xml
  languages/c/pom.xml
  languages/cpp/pom.xml
  languages/csharp/pom.xml
  languages/emf-metamodel-dynamic/pom.xml
  languages/emf-metamodel/pom.xml
  languages/emf-model/pom.xml
  languages/golang/pom.xml
  languages/java/pom.xml
  languages/javascript/pom.xml
  languages/kotlin/pom.xml
  languages/llvmir/pom.xml
  languages/multi-language/pom.xml
  languages/pom.xml
  languages/python-3/pom.xml
  languages/rlang/pom.xml
  languages/rust/pom.xml
  languages/scala/pom.xml
  languages/scheme/pom.xml
  languages/scxml/pom.xml
  languages/swift/pom.xml
  languages/text/pom.xml
  languages/typescript/pom.xml
  pom.xml
Labels: release

#2535 Increase JPlag revision to 6.3.0-SNAPSHOT
  pom.xml
Labels: release
