Repository jplag/JPlag, pull requests merged in 2025-03, with the labels that each got.

#2221 Migrate tailwind to v4
  report-viewer/package-lock.json
  report-viewer/package.json
  report-viewer/postcss.config.js
  report-viewer/src/App.vue
  report-viewer/src/components/ClusterGraph.vue
  report-viewer/src/components/ClusterRadarChart.vue
  report-viewer/src/components/ComparisonTableFilter.vue
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/components/ContainerComponent.vue
  report-viewer/src/components/DropDownSelector.vue
  report-viewer/src/components/InteractableComponent.vue
  report-viewer/src/components/LoadingCircle.vue
  report-viewer/src/components/NameElement.vue
  report-viewer/src/components/SearchBarComponent.vue
  report-viewer/src/components/TabbedContainer.vue
  report-viewer/src/components/ToastComponent.vue
  report-viewer/src/components/ToolTipComponent.vue
  report-viewer/src/components/VersionRepositoryReference.vue
  report-viewer/src/components/distributionDiagram/DistributionDiagram.vue
  report-viewer/src/components/distributionDiagram/DistributionDiagramOptions.vue
  report-viewer/src/components/fileDisplaying/CodeLine.vue
  report-viewer/src/components/fileDisplaying/CodePanel.vue
  report-viewer/src/components/fileDisplaying/FilesContainer.vue
  report-viewer/src/components/fileDisplaying/MatchList.vue
  report-viewer/src/components/optionsSelectors/OptionComponent.vue
  report-viewer/src/components/optionsSelectors/OptionsSelectorComponent.vue
  report-viewer/src/style.css
  report-viewer/src/viewWrapper/ClusterViewWrapper.vue
  report-viewer/src/viewWrapper/ComparisonViewWrapper.vue
  report-viewer/src/viewWrapper/InformationViewWrapper.vue
  report-viewer/src/viewWrapper/OverviewViewWrapper.vue
  report-viewer/src/views/ClusterView.vue
  report-viewer/src/views/ComparisonView.vue
  report-viewer/src/views/ErrorView.vue
  report-viewer/src/views/FileUploadView.vue
  report-viewer/src/views/InformationView.vue
  report-viewer/src/views/OldVersionRedirectView.vue
  report-viewer/src/views/OverviewView.vue
  report-viewer/tailwind.config.js
  report-viewer/tests/unit/components/comparisonTable/ComparisonTableFilter.test.ts
  report-viewer/tests/unit/components/optionsSelectors/OptionSelectorComponent.test.ts
  report-viewer/vite.config.ts
Labels: enhancement, dependencies, minor

#2232 Fix documentation regarding language options
  README.md
  docs/1.-How-to-Use-JPlag.md
Labels: bug, minor

#2235 Clean up the language interfaces
  language-api/src/main/java/de/jplag/Language.java
  languages/c/src/main/java/de/jplag/c/CLanguage.java
  languages/cpp/src/main/java/de/jplag/cpp/CPPLanguage.java
  languages/csharp/src/main/java/de/jplag/csharp/CSharpLanguage.java
  languages/emf-metamodel-dynamic/src/main/java/de/jplag/emf/dynamic/DynamicEmfLanguage.java
  languages/emf-metamodel/src/main/java/de/jplag/emf/EmfLanguage.java
  languages/emf-model/src/main/java/de/jplag/emf/model/EmfModelLanguage.java
  languages/golang/src/main/java/de/jplag/golang/GoLanguage.java
  languages/java/src/main/java/de/jplag/java/JavaLanguage.java
  languages/javascript/src/main/java/de/jplag/javascript/JavaScriptLanguage.java
  languages/kotlin/src/main/java/de/jplag/kotlin/KotlinLanguage.java
  languages/llvmir/src/main/java/de/jplag/llvmir/LLVMIRLanguage.java
  languages/python-3/src/main/java/de/jplag/python3/PythonLanguage.java
  languages/rlang/src/main/java/de/jplag/rlang/RLanguage.java
  languages/rust/src/main/java/de/jplag/rust/RustLanguage.java
  languages/scheme/src/main/java/de/jplag/scheme/SchemeLanguage.java
  languages/scxml/src/main/java/de/jplag/scxml/ScxmlLanguage.java
  languages/swift/src/main/java/de/jplag/swift/SwiftLanguage.java
  languages/text/src/main/java/de/jplag/text/NaturalLanguage.java
  languages/typescript/src/main/java/de/jplag/typescript/TypeScriptLanguage.java
Labels: enhancement, minor, language

#2272 Update report readme
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
Labels: bug, minor, report-viewer

#2259 Apply automated clean-up operations
  core/src/main/java/de/jplag/csv/HardcodedCsvDataMapper.java
  core/src/main/java/de/jplag/csv/ReflectiveCsvDataMapper.java
  core/src/main/java/de/jplag/csv/comparisons/CsvComparisonOutput.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/test/java/de/jplag/NewJavaFeaturesTest.java
  core/src/test/java/de/jplag/clustering/ClusterTest.java
  core/src/test/java/de/jplag/clustering/ClusteringAdapterTest.java
  core/src/test/java/de/jplag/clustering/algorithm/AgglomerativeClusteringTest.java
  core/src/test/java/de/jplag/clustering/algorithm/GaussianProcessTest.java
  core/src/test/java/de/jplag/clustering/algorithm/SpectralClusteringTest.java
  core/src/test/java/de/jplag/clustering/preprocessors/CumulativeDistributionFunctionPreprocessorTest.java
  core/src/test/java/de/jplag/clustering/preprocessors/PercentilePreprocessorTest.java
  core/src/test/java/de/jplag/clustering/preprocessors/PreprocessingTestBase.java
  core/src/test/java/de/jplag/clustering/preprocessors/ThresholdPreprocessorTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/ClusteringResultMapperTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/ComparisonReportWriterTest.java
  core/src/test/java/de/jplag/reporting/reportobject/mapper/MetricMapperTest.java
  endtoend-testing/src/main/java/de/jplag/endtoend/helper/FileHelper.java
  endtoend-testing/src/main/java/de/jplag/endtoend/model/ComparisonIdentifier.java
  endtoend-testing/src/main/java/de/jplag/endtoend/model/Options.java
  endtoend-testing/src/test/java/de/jplag/endtoend/EndToEndSuiteTest.java
  languages/c/src/main/java/de/jplag/c/NewlineStream.java
  languages/c/src/main/java/de/jplag/c/Scanner.java
  languages/emf-model/src/main/java/de/jplag/emf/model/parser/DynamicModelParser.java
  languages/emf-model/src/test/java/de/jplag/emf/model/MinimalModelInstanceTest.java
  languages/java/src/main/java/de/jplag/java/Parser.java
  languages/rlang/src/test/java/de/jplag/rlang/RLanguageTest.java
  languages/rust/src/test/java/de/jplag/rust/RustLanguageTest.java
  languages/scala/src/test/java/de/jplag/scala/ScalaLanguageTest.java
  languages/scheme/src/main/java/de/jplag/scheme/Parser.java
  languages/swift/src/main/java/de/jplag/swift/grammar/SwiftSupport.java
  languages/swift/src/test/java/de/jplag/swift/SwiftFrontendTest.java
Labels: enhancement, minor
