Repository jplag/JPlag, pull requests merged in 2025-02, with the labels that each got.

#2169 Remove report viewer patch
  README.md
Labels: enhancement, minor

#2170 Add all dependencies to coverage report
  .github/workflows/scripts/checkCoverage.py
  .github/workflows/verify-coverage-report.yml
  coverage-report/pom.xml
Labels: enhancement, minor

#2075 Added the option to specify a result file with --move VIEW
  README.md
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/options/CliOptions.java
  cli/src/main/java/de/jplag/cli/picocli/CliInputHandler.java
  cli/src/test/java/de/jplag/cli/ModeTest.java
  cli/src/test/java/de/jplag/cli/test/CliArgument.java
  cli/src/test/java/de/jplag/cli/test/CliResult.java
  cli/src/test/java/de/jplag/cli/test/CliTest.java
  docs/1.-How-to-Use-JPlag.md
Labels: enhancement, minor

#2171 Add report viewer wiki chapter
  docs/7.-Report-Viewer.md
  docs/8.-Clustering-of-Submissions.md
  docs/images/7_anoneye_dark.png
  docs/images/7_anoneye_light.png
  docs/images/7_cluster_dark.png
  docs/images/7_cluster_light.png
  docs/images/7_comparison_dark.png
  docs/images/7_comparison_light.png
  docs/images/7_information_dark.png
  docs/images/7_information_light.png
  docs/images/7_landing_dark.png
  docs/images/7_landing_light.png
  docs/images/7_overview_dark.png
  docs/images/7_overview_light.png
  docs/images/7_radar_dark.png
  docs/images/7_radar_light.png
Labels: enhancement, report-viewer, wiki

#2172 Warning when report viewer not included
  cli/src/main/java/de/jplag/cli/JPlagRunner.java
  cli/src/main/java/de/jplag/cli/server/ReportViewer.java
Labels: enhancement, minor

#2168 Added automatic mode selection
  README.md
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/options/CliOptions.java
  cli/src/main/java/de/jplag/cli/options/JPlagMode.java
  cli/src/test/java/de/jplag/cli/ModeTest.java
  docs/1.-How-to-Use-JPlag.md
Labels: enhancement, minor

#2189 Set JPlag revision to v6.0.0
  pom.xml
Labels: release

#2187 6.0.0 hosted report viewer
  assets/index-Bf0Z0whY.js
  assets/index-DPPiA3g-.css
  index.html
Labels: report-viewer, release

#2192 Update version.json
  report-viewer/src/version.json
Labels: release

#2205 Fix language export and import in report
  core/src/main/java/de/jplag/reporting/jsonfactory/serializer/LanguageSerializer.java
  core/src/main/java/de/jplag/reporting/reportobject/ReportObjectFactory.java
  core/src/main/java/de/jplag/reporting/reportobject/model/OverviewReport.java
  report-viewer/src/model/Language.ts
  report-viewer/src/model/factories/OptionsFactory.ts
Labels: bug, minor, report-viewer

#2206 Automatic code analysis of report viewer
  report-viewer/package-lock.json
  report-viewer/src/components/distributionDiagram/DistributionDiagram.vue
  report-viewer/src/model/fileHandling/ZipFileHandler.ts
  report-viewer/src/utils/ColorUtils.ts
  report-viewer/src/views/InformationView.vue
Labels: bug, minor, report-viewer

#2179 Greedy String Tiling out of bounds
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/comparison/GreedyStringTiling.java
  core/src/main/java/de/jplag/comparison/LongestCommonSubsquenceSearch.java
  core/src/main/java/de/jplag/comparison/SubmissionTuple.java
  core/src/main/java/de/jplag/comparison/SubsequenceHashLookupTable.java
  core/src/main/java/de/jplag/comparison/TokenValueMapper.java
  core/src/main/java/de/jplag/logging/ProgressBarType.java
  core/src/main/java/de/jplag/strategy/ComparisonStrategy.java
  core/src/main/java/de/jplag/strategy/ParallelComparisonStrategy.java
  core/src/test/java/de/jplag/merging/MergingTest.java
Labels: bug, minor

#2208 Ensure that IPv4 network stack is preferred.
  cli/src/main/java/de/jplag/cli/CLI.java
  cli/src/main/java/de/jplag/cli/server/ReportViewer.java
Labels: bug, minor, report-viewer
