Repository jplag/JPlag, pull requests merged in 2025-06, with the labels that each got.

#2414 Normalize WITH token braces to match BEGIN/END convention
  languages/python-3/src/main/java/de/jplag/python3/Python3TokenType.java
Labels: bug, minor, language

#2422 Switch pre-commit to bash
  gitHooks/hooks/pre-commit
Labels: enhancement, minor

#2421 CheckResultFileWritableTest - Files still writable after calling setWritable(false)
  cli/src/test/java/de/jplag/cli/CheckResultFileWritableTest.java
Labels: bug, minor

#2396 Introduce asymmetric matches
  core/src/main/java/de/jplag/JPlag.java
  core/src/main/java/de/jplag/JPlagComparison.java
  core/src/main/java/de/jplag/Match.java
  core/src/main/java/de/jplag/comparison/GreedyStringTiling.java
  core/src/main/java/de/jplag/merging/MatchMerging.java
  core/src/main/java/de/jplag/reporting/jsonfactory/ComparisonReportWriter.java
  core/src/main/java/de/jplag/reporting/reportobject/model/Match.java
  core/src/test/java/de/jplag/BasicFunctionalityTest.java
  core/src/test/java/de/jplag/merging/MatchMergingTest.java
  report-viewer/src/components/fileDisplaying/FilesContainer.vue
  report-viewer/src/components/fileDisplaying/MatchList.vue
  report-viewer/src/model/BaseCodeReport.ts
  report-viewer/src/model/Match.ts
  report-viewer/src/model/MatchInSingleFile.ts
  report-viewer/src/model/factories/ComparisonFactory.ts
Labels: enhancement, major

#2437 Use relative paths in report
  core/src/main/java/de/jplag/options/JPlagOptions.java
  core/src/main/java/de/jplag/reporting/jsonfactory/serializer/FileSerializer.java
Labels: bug, minor, report-viewer

#2397 Improve cluster graph
  report-viewer/src/components/ClusterGraph.vue
  report-viewer/src/components/ComparisonsTable.vue
  report-viewer/src/utils/ColorUtils.ts
  report-viewer/src/views/ClusterView.vue
Labels: enhancement, minor, report-viewer

#2412 Improve the comparison algorithm performance for large workloads
  core/src/main/java/de/jplag/comparison/LongestCommonSubsequenceSearch.java
  core/src/main/java/de/jplag/comparison/SubsequenceHashLookupTable.java
  core/src/main/java/de/jplag/comparison/TokenValueMapper.java
  core/src/main/java/de/jplag/exceptions/ComparisonException.java
  core/src/main/java/de/jplag/logging/ProgressBarLogger.java
  core/src/test/java/de/jplag/merging/MatchMergingTest.java
Labels: enhancement, minor

#2465 Fix bugs with failed submissions display
  report-viewer/src/components/TextInformation.vue
  report-viewer/src/views/OverviewView.vue
  report-viewer/tests/e2e/Comparison.spec.ts
  report-viewer/tests/e2e/Information.spec.ts
Labels: bug, minor, report-viewer

#2462 Improve naming in the core algorithm
  core/src/main/java/de/jplag/comparison/GreedyStringTiling.java
  core/src/main/java/de/jplag/comparison/LongestCommonSubsequenceSearch.java
  core/src/main/java/de/jplag/comparison/RollingTokenHashTable.java
  core/src/main/java/de/jplag/comparison/TokenSequenceMapper.java
  core/src/main/java/de/jplag/logging/ProgressBarType.java
  core/src/test/java/de/jplag/merging/MatchMergingTest.java
Labels: enhancement, minor
